Instrucciones

1. Preparación del Entorno
* Asegúrate de tener instalado Pandas en tu entorno de trabajo.
* Utiliza el archivo retail_sales.csv del proyecto inicial. Si aún no lo tienes, descarga el archivo correspondiente.
2. Cargar los Datos
* Carga el archivo retail_sales.csv en un DataFrame de Pandas.
* Muestra las primeras 10 filas del DataFrame para confirmar que los datos se han cargado correctamente.
3. Exploración Inicial de los Datos
* Muestra las últimas 5 filas del DataFrame.
* Utiliza el método info() para obtener información general sobre el DataFrame, incluyendo el número de entradas, nombres de las columnas, tipos de datos y memoria utilizada.
* Genera estadísticas descriptivas del DataFrame utilizando el método describe().
4. Inspección de los Datos
* Inspecciona los tipos de datos de cada columna utilizando el atributo dtypes.
* Cuenta los valores únicos en la columna Producto utilizando el método value_counts().
* Muestra todos los valores únicos en la columna Tienda utilizando el método unique().
5. Filtrado de Datos
* Filtra el DataFrame para mostrar solo las filas donde las ventas (Ventas) sean mayores a 50.
* Filtra el DataFrame para mostrar solo las filas donde el precio (Precio) sea menor a 0.5.
* Utilizando el método query(), filtra el DataFrame para mostrar las filas donde el producto sea Manzanas y las ventas sean mayores a 30.
6. Slicing de Datos
* Selecciona y muestra solo las columnas Producto y Ventas del DataFrame.
* Utilizando loc[], selecciona y muestra las filas de la 5 a la 10 (inclusive) y las columnas Producto y Tienda.
* Utilizando iloc[], selecciona y muestra las primeras 5 filas y las primeras 3 columnas del DataFrame.

1. PREPARACIÓN DEL ENTORNO

In [ ]:
import pandas as pd
df = pd.read_csv('/content/retail_sales_dataset.csv')

2. CARGAR LOS DATOS

In [ ]:
df

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [ ]:
# Las 10 primeras filas del df

df.head(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200

3. EXPLORACIÓN INICIAL DE LOS DATOS

In [ ]:
# Últimas 5 filas

df.tail()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [ ]:
# Usando método info() para obtener información general del df

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB

In [ ]:
# Obtener estadísticas descriptivas del df

df.describe()

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

4. INSPECCIÓN DE DATOS

In [ ]:
# Inspecciona los tipos de datos de las columnas

df.dtypes

Transaction ID       int64
Date                object
Customer ID         object
Gender              object
Age                  int64
Product Category    object
Quantity             int64
Price per Unit       int64
Total Amount         int64
dtype: object

In [ ]:
# Cuántos valores únicos hay en la columna 'Producto'

###COMENTARIOS: Se identifica una discrepancia entre las instrucciones de este CORE y el esquema del dataset descargado de Kaggle.
###             En el dataset de ventas NO EXISTE una columna llamada 'Producto'. Esto se confirma en la exploración inicial de los datos con el método info()
###             y también se valida con la inspección de los datos en cada columna usando dtypes. Con la finalidad de demostrar las técnicas o métodos,
###             se utilizará la columna 'Product Category' pero ésta NO SERÁ RENOMBRADA a 'Producto'. Categoría de producto abarca un 'concepto más general' ya que
###             engloba 'subgrupos' como puede ser Electrónica, que engloba 'Productos' como tecnología, dispositivos, gaming, etc, o Vestimenta, que engloba
###             'Productos' como calzado, accesorios, vestuario, etc.

df['Product Category'].value_counts()

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

In [ ]:
# Encontrar los valores únicos en la columna 'Tienda'

###COMENTARIOS: De igual forma que en el ejercicio anterior, NO EXISTE una columna denominada 'Tienda' por lo que nos arrojaría como resultado un vacío.
###             Para demostrar el método, se utilizará la columna 'Gender' que arrojará un array con los valores únicos presentes en la columna del género.
###             Cabe destacar que para este caso no hay una columna o dato que permita construir o calcular una nueva columna, denominada 'Tienda', en base a los
###             datos presentes en el dataset de ventas retail. Anteriormente df.info() ilustró todas las columnas presentes en el df y sin presencia de valores
###             no nulos. Las columnas por sí solas o con estadística descriptiva o inspeccionando los tipos de datos con el método dtypes,
###             ninguna es capaz de entregar información relacionada con un espacio fisico dado que los datos registrados reportan información de los consumidores o
###             las ventas.

df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

5. FILTRADO DE DATOS

In [ ]:
# Filtrar por ventas mayores a 50

###COMENTARIOS: No existe una columna llamada 'Ventas', sin embargo en análisis de datos tiene más sentido que éste término se refiera al valor monetario (dinero)
###             y no a cuántas piezas se vendieron. Para este caso, aquella columna con 'Total Amount' es la que mejor representa el concepto de 'Ventas'.
###             Se procederá a renombrar la columna de 'Total Amount' como 'Ventas', sin antes hacer una copia del df para evitar sobreescribir el df original.

df_copia = df.copy()
df1_copia = df_copia.rename(columns = {'Total Amount': 'Ventas'})
df1_copia[df1_copia['Ventas'] > 50]

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Ventas
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
...,...,...,...,...,...,...,...,...,...
993,994,2023-12-18,CUST994,Female,51,Beauty,2,500,1000
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [ ]:
# Filtrar por 'Precio' menor a 0.5

###COMENTARIOS: El nombre 'Precio' NO EXISTE en el dataset. Sin embargo hay una categoría que representa muy bien esta variable y es la columna 'Price per Unit'.
###             Por lo tanto, como en el caso anterior, se renombrará la columna 'Price per Unit' por 'Precio' entendiendo que ambos conceptos son similares. Pero,
###             surge otro problema, y es que el precio mínimo, como se aprecia en las estadísticas descriptivas, es de 30 unidades monetarias y al usar 0.5
###             indicado en las instrucciones el resultado será 'vacío'. Por ende se reemplazará el valor de 0.5 por 50, valor totalmente al azar
###             pero dentro del rango de precios.

df2_copia = df1_copia.rename(columns = {'Price per Unit': 'Precio'})
df2_copia[df2_copia['Precio'] < 50]

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Precio,Ventas
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
11,12,2023-10-30,CUST012,Male,35,Beauty,3,25,75
...,...,...,...,...,...,...,...,...,...
991,992,2023-08-21,CUST992,Female,57,Electronics,2,30,60
994,995,2023-04-30,CUST995,Female,41,Clothing,1,30,30
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [ ]:
# Utilizando query() para filtrar el df y que muestre las filas donde 'Producto' sea 'Manzanas' y 'Ventas' sean mayores a 30

###COMENTARIOS: Columna 'Producto' se mencionó que no existía, y como lo más cercano a esta nombre es 'Product Category', se realiza el método .unique()
###             a ésta columna donde no hay rastros de la palabra 'Manzanas'. Como se verificó que la cantidad de Non-Null count = N° de registros (no hay NaN),
##              con dtypes se mostró aquellas columnas con valores tipo 'object', que es donde probablemente se encuentre la palabra 'Manzanas', dado que el resto de
###             columnas son números enteros, entonces se procede a usar el método .str.contains() para comprobar finalmente que 'Manzanas' no se encuentra
###             en el dataset. Como la idea es entender las metodologías, 'Manzanas' será reemplazada por la categoría de producto
###             'Clothing' por el hecho solamente de ser la categoría con la mayor cantidad de valores únicos que podría representar mayor demanda,
###             entendiéndose que no hay data que represente el producto 'Manzanas' y por tanto el resultado sería 'vacío'.



print(df['Product Category'].unique())
print()
df2_copia.query("`Product Category` == 'Clothing' & Ventas > 30")   # Product Category tiene espacios y Python pensará que Product y Category son dos cosas distintas
                                                                    # dando error de sintaxis. NOMBRES DE COLUMNAS CON ESPACIOS VAN ENTRE COMILLAS INVERSAS (backticks)

['Beauty' 'Clothing' 'Electronics']

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Precio,Ventas
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200
10,11,2023-02-14,CUST011,Male,23,Clothing,2,50,100
...,...,...,...,...,...,...,...,...,...
985,986,2023-01-17,CUST986,Female,49,Clothing,2,500,1000
986,987,2023-04-29,CUST987,Female,30,Clothing,3,300,900
987,988,2023-05-28,CUST988,Female,63,Clothing,3,25,75
990,991,2023-12-26,CUST991,Female,34,Clothing,2,50,100
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50

#### ***COMENTARIO ADICIONAL***: ABAJO SE ENCUENTRA EL MÉTODO .str.contains() PARA DEMOSTRAR QUE EN LAS CATEGORÍAS DONDE HAY PRESENCIA DE DATOS TIPO OBJECT, NINGUNA COINCIDE CON LA PALABRA 'Manzanas'

In [ ]:
df_manzanas = df[
    df['Customer ID'].str.contains('Manzanas') |
    df['Gender'].str.contains('Manzanas') |
    df['Product Category'].str.contains('Manzanas')
]

print(f"Cantidad de palabras 'Manzanas': {len(df_manzanas)}")

Cantidad de palabras 'Manzanas': 0

6. SLICING DE DATOS

In [ ]:
# Mostrar columnas 'Producto' y 'Ventas' del df

###COMENTARIOS: Columna 'Producto' será reemplazada por 'Product Category' para observar solamente cómo se ejecuta el slicing.

df2_copia[['Product Category', 'Ventas']]

    Product Category  Ventas
0             Beauty     150
1           Clothing    1000
2        Electronics      30
3           Clothing     500
4             Beauty     100
..               ...     ...
995         Clothing      50
996           Beauty      90
997           Beauty     100
998      Electronics     150
999      Electronics     120

[1000 rows x 2 columns]

In [ ]:
# Utilizar método loc[] para mostrar las filas 5-10 inclusive, y columnas 'Producto' y 'Tienda'

###COMENTARIOS: Mismo procedimiento que se ha trabajado en este CORE. Recordar que para fines ilustrativos 'Producto' será 'Product Category'
###             y 'Tienda' será 'Gender' como se hizo en ejercicios previos, pero ambos conceptos no existen en el df.

df2_copia.loc[5:10, ['Product Category', 'Gender']]

   Product Category  Gender
5            Beauty  Female
6          Clothing    Male
7       Electronics    Male
8       Electronics    Male
9          Clothing  Female
10         Clothing    Male

In [ ]:
# Utilizar método iloc[] para mostrar las primeras 5 filas y primeras 3 columnas

# Solo mencionar que el resultado es el mismo si se hace con el df original o con df2_copia dado que las columnas pedidas están en el dataset.
df2_copia.iloc[0:5, 0:3]

   Transaction ID        Date Customer ID
0               1  2023-11-24     CUST001
1               2  2023-02-27     CUST002
2               3  2023-01-13     CUST003
3               4  2023-05-21     CUST004
4               5  2023-05-06     CUST005