Instrucciones

1. Transformación de Datos
* Crea nuevas columnas: Basándonos en los datos existentes, crea nuevas columnas que sean útiles para el análisis. Por ejemplo, calcula el ingreso total por venta y normaliza las ventas.
* Clasifica los datos: Crea una columna que clasifique las ventas en categorías significativas (e.g., ‘Alta’, ‘Media’, ‘Baja’).
2. Agrupación y Agregación
* Agrupación por múltiples columnas: Realiza agrupaciones por categorías como producto y tienda, producto y mes, etc.
* Aplicar funciones de agregación: Utiliza funciones como sum, mean, count, min, max, std, y var para obtener estadísticas descriptivas de cada grupo.
3. Análisis Personalizado con apply
* Función personalizada: Aplica funciones personalizadas para realizar análisis específicos que no se pueden lograr con las funciones de agregación estándar.
* Ejemplo de uso avanzado: Calcula la desviación de cada venta respecto a la media de su grupo.
4. Documentación
* Comentarios claros: Documenta claramente cada paso del análisis, explicando qué se hizo y por qué se hizo.
* Código legible: Asegúrate de que el código sea legible y esté bien comentado.

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/retail_sales_dataset.csv')
df

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

TRANSFORMACIÓN DE DATOS

In [ ]:
df_copia = df.copy()

In [ ]:
# Se crearán nuevas columnas como total a pagar con el iva

df_copia['Tax Amount'] = df_copia['Total Amount'] * 0.19
df_copia['Final Price'] = df_copia['Total Amount'] + df_copia['Tax Amount']
df_copia

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Tax Amount,Final Price
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,28.5,178.5
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,190.0,1190.0
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,5.7,35.7
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,95.0,595.0
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,19.0,119.0
...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,9.5,59.5
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,17.1,107.1
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,19.0,119.0
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,28.5,178.5
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,22.8,142.8

In [ ]:
# Normalizando las ventas

# Esto permite comparar por ejemplo el rendimiento de las ventas en una escala de 0 a 1
max_value = df_copia['Final Price'].max()
min_value = df_copia['Final Price'].min()
df_copia['Sales Normalized'] = df_copia['Final Price'].apply(lambda x: (x - min_value) / (max_value - min_value))
df_copia

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Tax Amount,Final Price,Sales Normalized
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,28.5,178.5,0.063291
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,190.0,1190.0,0.493671
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,5.7,35.7,0.002532
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,95.0,595.0,0.240506
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,19.0,119.0,0.037975
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,9.5,59.5,0.012658
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,17.1,107.1,0.032911
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,19.0,119.0,0.037975
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,28.5,178.5,0.063291
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,22.8,142.8,0.048101

In [ ]:
# Categorizando las ventas

# Se traen las estadísticas descriptivas para utilizar los valores y quizás definir una función

df_copia.describe()

,Transaction ID,Age,Quantity,Price per Unit,Total Amount,Tax Amount,Final Price,Sales Normalized
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000
mean,500.500000,41.39200,2.514000,179.890000,456.000000,86.64000,542.640000,0.218228
std,288.819436,13.68143,1.132734,189.681356,559.997632,106.39955,666.397182,0.283543
min,1.000000,18.00000,1.000000,25.000000,25.000000,4.75000,29.750000,0.000000
25%,250.750000,29.00000,1.000000,30.000000,60.000000,11.40000,71.400000,0.017722
50%,500.500000,42.00000,3.000000,50.000000,135.000000,25.65000,160.650000,0.055696
75%,750.250000,53.00000,4.000000,300.000000,900.000000,171.00000,1071.000000,0.443038
max,1000.000000,64.00000,4.000000,500.000000,2000.000000,380.00000,2380.000000,1.000000

In [ ]:
# Categorizando las ventas podríamos usar los cuantiles (.quantile()) para que haya una distribución justificada y no arbitraria

precio_bajo = df_copia['Final Price'].quantile(0.25)
precio_alto = df_copia['Final Price'].quantile(0.75)

def clasificar_venta(venta):
  if venta <= precio_bajo:
    return 'Low'
  elif venta >= precio_alto:
    return 'High'
  else:
    return 'Medium'

# Aplicando apply para que se aplique la función a cada columna del precio final
df_copia['Sales Category'] = df_copia['Final Price'].apply(clasificar_venta)
df_copia

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Tax Amount,Final Price,Sales Normalized,Sales Category
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,28.5,178.5,0.063291,Medium
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,190.0,1190.0,0.493671,High
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,5.7,35.7,0.002532,Low
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,95.0,595.0,0.240506,Medium
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,19.0,119.0,0.037975,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,9.5,59.5,0.012658,Low
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,17.1,107.1,0.032911,Medium
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,19.0,119.0,0.037975,Medium
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,28.5,178.5,0.063291,Medium
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,22.8,142.8,0.048101,Medium

AGRUPACIÓN Y AGREGACIÓN

In [ ]:
# Agrupación de categoría por producto y género. Esto puede ayudar en análisis de datos para revelar preferencias en consumo según segmento demográfico, en este caso,
# según el género de la persona

df_copia.groupby(['Product Category', 'Gender'])['Final Price'].agg(
    ['count', 'sum', 'mean', 'min', 'max', 'std', 'var']).rename(columns = {'sum': 'Total Sales', 'mean': 'Average Sale', 'min': 'Lowest Price', 'max': 'Max. Price'})

                         count  Total Sales  Average Sale  Lowest Price  \
Product Category Gender
Beauty           Female    166     89047.70    536.431928         29.75
                 Male      141     81735.15    579.681915         29.75
Clothing         Female    174     96717.25    555.846264         29.75
                 Male      177     88422.95    499.564689         29.75
Electronics      Female    170     91314.65    537.145000         29.75
                 Male      172     95402.30    554.664535         29.75

                         Max. Price         std            var
Product Category Gender
Beauty           Female      2380.0  641.094698  411002.411671
                 Male        2380.0  705.550672  497801.751367
Clothing         Female      2380.0  686.649624  471487.706503
                 Male        2380.0  623.698322  388999.597056
Electronics      Female      2380.0  652.887129  426261.602919
                 Male        2380.0  698.684346  488159.814846

Existe una alta preferencia por la categoría vesturario y electrónica, se consume y gasta bastante en estos sectores y que tiene sentido en un mundo donde la tecnología prima. Por otro lado en la vestimenta, la ropa básica se considera necesidad básica (protección contra el clima, salud) pero la moda o el lujo son más secundarias ya que mejoran la calidad de vida o social pero no son vitales para la supervivencia, sin embargo, de igual forma se gasta bastante en este sector ya sea para mantener un alto status social, autoestima, satisfacción personal, etc. Para los productos de belleza, existe una gran preferencia del cuidado e higiene personal por parte de las mujeres vs los hombres

In [ ]:
# Análisis personalizado: se utilizará una función para calcular cuánto se aleja cada venta respecto del promedio global
# Esto permite conocer si la transacción fue normal o extraordinaria

prom_global = df_copia['Final Price'].mean()

# Se define la función 'calc_resultado' que devolverá la diferencia del valor de la columna 'Final Price' y el promedio global

def calc_resultado(valor):
  resultado = valor - prom_global
  # Uso de condicional para determinar el rendimiento de la venta
  if resultado > 0:
    return 'Outperforming🔥'
  elif resultado == 0:
    return 'On Target✅'
  else:
    return 'Underperforming❌'

# Se aplica la función a cada columna del precio final y se devuelve a una nueva columna de rendimiento
df_copia['Transaction Rating'] = df_copia['Final Price'].apply(calc_resultado)
df_copia

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Tax Amount,Final Price,Sales Normalized,Sales Category,Transaction Rating
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,28.5,178.5,0.063291,Medium,Underperforming❌
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,190.0,1190.0,0.493671,High,Outperforming🔥
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,5.7,35.7,0.002532,Low,Underperforming❌
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,95.0,595.0,0.240506,Medium,Outperforming🔥
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,19.0,119.0,0.037975,Medium,Underperforming❌
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,9.5,59.5,0.012658,Low,Underperforming❌
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,17.1,107.1,0.032911,Medium,Underperforming❌
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,19.0,119.0,0.037975,Medium,Underperforming❌
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,28.5,178.5,0.063291,Medium,Underperforming❌
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,22.8,142.8,0.048101,Medium,Underperforming❌

In [ ]:
# Guarda el DataFrame 'df_csv' como un archivo CSV en la ruta especificada ('/content/salida.csv').
# El parámetro 'index=False' asegura que el índice de las filas no se incluya en el archivo CSV.
# Código aportado por ayudante Cristián Sánchez
df_copia.to_csv('/content/retail_sales_dataset_limpio.csv', index=False)